/**
 * URL paths (no leading slash) rendered by the legacy `switch` in `src/app/[...slug]/page.tsx`.
 * When adding a new marketing route there, add the same slug here so CMS sync can include it.
 */
export const LEGACY_MARKETING_PAGE_SLUGS = [
  'about-us',
  'contact-us',
  'consultation-form',
  'career',
  'clip-on-or-stick-on',
  'clip-on-or-stick-on/clip-on-hair-system',
  'clip-on-or-stick-on/stick-on-hair-system',
  'clip-on-system-lifespan',
  'hair-patch-vs-hair-system',
  'hair-transplant',
  'products',
  'results',
  'scalp-micropigmentation',
  'stick-on-system-lifespan',
  'will-my-hairline-look-real',
  'hair-patch-for-men',
  'hair-replacement-for-men',
  'hair-wigs-for-men',
  'swiss-lace-hair-patch',
  'skin-base-hair-systems',
  'clip-on-hair-system',
  'customized-hair-systems',
  'crown-area-patch',
  'non-surgical-hair-replacement-in-mumbai',
  'non-surgical-hair-replacement-systems-in-delhi',
  'non-surgical-hair-replacement-in-bangalore',
  'non-surgical-hair-replacement-in-chennai',
  'non-surgical-hair-replacement-in-hyderabad',
  'non-surgical-hair-replacement-in-punjab',
  'non-surgical-hair-replacement-in-rajasthan',
  'non-surgical-hair-replacement-in-surat',
  'non-surgical-hair-replacement-for-men-in-pune',
  'hair-replacement-systems-for-men-in-goa',
  'hair-replacement-systems-for-men-in-kolkata',
  'hair-replacement-systems-for-men-in-lucknow',
  'hair-replacement-systems-in-ahmedabad',
  'hair-wigs-for-men-in-mumbai',
  'hair-wigs-for-men-in-delhi',
  'hair-wigs-for-men-in-bangalore',
  'hair-wigs-for-men-in-chennai',
  'hair-wigs-for-men-in-hyderabad',
  'hair-wigs-for-men-in-kolkata',
  'hair-wigs-for-men-in-pune',
  'australian-mirage-hair-patch',
  'common-questions',
  'support',
  'disclaimer',
  'front-hairline-patch',
  'hair-replacement-for-men-in-chennai',
  'hair-replacement-for-men-in-punjab',
  'hair-replacement-for-men-in-rajasthan',
  'hair-replacement-services',
  'non-surgical-hair-replacement',
  'privacy-policy',
  'terms-of-service',
  'front-hairline-transplant-2',
  'tape-glue-hair-system',
  'clipon-tape-hair-system',
  'full-lace-french-lace-hair-systems',
] as const

export type LegacyMarketingPageSlug = (typeof LEGACY_MARKETING_PAGE_SLUGS)[number]
