/**
 * Maps FlexiFunnel block IDs (block-04-hero, etc.) to semantic section keys
 * used by funnel-desktop.css data-funnel-section selectors.
 */
const BLOCK_SECTION_ALIASES: Record<string, string> = {
  'block-01-sticky': 'stick-cta',
  'block-01-hero': 'hero-black-card',
  'block-03-sticky-marquee': 'sticky-marquee',
  'block-03-sticky': 'sticky-marquee',
  'block-04-hero': 'hero-black-card',
  'block-07-the-secret-behind-our-natural-hairline': 'the-secret-behind-natural-hairline',
  'block-08-this-is-for-you-if': 'when-hair-loss-starts',
  'block-08-exclusive-offer': 'exclusive-offer',
  'block-23-benefits-of-the-stick-on-system': 'stick-on-benefits',
  'block-05-real-hair-or-illusion': 'real-hair-or-illusion',
  'block-09-real-hair-or-illusion': 'real-hair-or-illusion',
  'block-14-from-consultation': 'how-it-works',
  'block-09-the-secret-behind-our-natural-hairline': 'the-secret-behind-natural-hairline',
  'block-10-real-hair-or-illusion-watch-decide': 'real-hair-or-illusion',
  'block-08-here-s-why-we-re-the-first-choice-for-men': 'heres-why-we-are-the-first-choice-for-men',
  'block-10-firstchoice': 'heres-why-we-are-the-first-choice-for-men',
  'block-11-here-s-why-we-re': 'heres-why-we-are-the-first-choice-for-men',
  'block-13-why-we-re-the': 'heres-why-we-are-the-first-choice-for-men',
  'block-11-happyclients': 'hear-from-our-happy-clients',
  'block-12-hear-from-our-happy-clients': 'hear-from-our-happy-clients',
  'block-12-customization': 'customisation',
  'block-13-customization': 'customisation',
  'block-13-visit-to-final-look': 'how-it-works',
  'block-14-hear-from-our-happy-clients': 'hear-from-our-happy-clients',
  'block-13-world-s-thinnest': 'worlds-thinnest-hair-systems',
  'block-14-thinnest': 'worlds-thinnest-hair-systems',
  'block-15-bollywood-s': 'the-artist-behind-bollywood',
  'block-15-clients-say': 'what-our-clients-say',
  'block-15-what-our-clients-say': 'what-our-clients-say',
  'block-16-bollywood-s': 'the-artist-behind-bollywood',
  'block-16-happy-clients': 'hear-from-our-happy-clients',
  'block-16-what-our-clients-say': 'what-our-clients-say',
  'block-17-bollywood-s': 'the-artist-behind-bollywood',
  'block-17-whychooseus': 'why-choose-us',
  'block-19-moneyback': '100-money-back-guarantee',
  'block-19-100-money': '100-money-back-guarantee',
  'block-20-hair-transplant-vs-hair-system': 'hair-transplant-vs-hair-system',
  'block-21-what-makes-us-different': 'what-makes-us-different',
  'block-22-no-risk-just-results-100-satisfaction-guarantee': 'no-risks-just-results',
  'block-16-frequently-asked-questions': 'faqs',
  'block-21-frequently-asked-questions': 'faqs',
  'block-22-frequently-asked-questions': 'faqs',
  'block-23-frequently-asked-questions': 'faqs',
  'block-24-frequently-asked-questions': 'faqs',
  'block-24-our-location': 'our-location',
  'block-25-book-your-1-1-consultation': 'lets-start-with-a-consultation',
  'block-17-footer': 'privacy-and-disclaimer',
  'block-23-footer': 'privacy-and-disclaimer',
  'block-24-footer': 'privacy-and-disclaimer',
  'block-25-footer': 'privacy-and-disclaimer',
  'block-26-footer': 'privacy-and-disclaimer',
};

export function resolveFunnelSectionKey(sectionKey: string): string {
  return BLOCK_SECTION_ALIASES[sectionKey] ?? sectionKey;
}
